name: Dynamic README injection

on:
  workflow_dispatch:
  schedule:
    # runs at 12 AM UTC (5:30 AM IST)
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update this repo's Waka-README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          TARGET_BRANCH: master
          AUTHOR_NAME: Dhia Shalabi
          AUTHOR_EMAIL: dhia.shalabi@gmail.com
